//go:build ignore

// Command api_surface records and checks the documented exported Go surface.
// It intentionally includes public symbol documentation because documented
// behavior is part of the candidate compatibility contract.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

const generatedHeader = `# Code generated by go run ./scripts/api_surface.go; DO NOT EDIT.
#
# This baseline includes exported root-package declarations, their public
# documentation, methods, fields, constants, and the definitions behind
# root-level aliases to private implementation packages.

`

func main() {
	baseline := flag.String("baseline", "api/public-v0.6.txt", "baseline path")
	write := flag.Bool("write", false, "replace the baseline with the current surface")
	flag.Parse()

	current, err := currentSurface()
	if err != nil {
		fatal(err)
	}
	if *write {
		if err := os.MkdirAll(filepath.Dir(*baseline), 0o750); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(*baseline, current, 0o644); err != nil {
			fatal(err)
		}
		return
	}
	want, err := os.ReadFile(*baseline)
	if err != nil {
		fatal(fmt.Errorf("read API baseline: %w", err))
	}
	if bytes.Equal(want, current) {
		return
	}
	line, before, after := firstDifference(want, current)
	fatal(fmt.Errorf(
		"public API differs from %s at line %d\n  baseline: %s\n  current:  %s\nreview compatibility and run: go run ./scripts/api_surface.go -write",
		*baseline, line, before, after,
	))
}

func currentSurface() ([]byte, error) {
	root, err := goDoc(".")
	if err != nil {
		return nil, err
	}
	aliases, err := exportedAliases()
	if err != nil {
		return nil, err
	}
	var out bytes.Buffer
	out.WriteString(generatedHeader)
	out.Write(root)
	if len(aliases) > 0 {
		out.WriteString("\n\nALIASED TYPE DEFINITIONS\n\n")
	}
	for _, alias := range aliases {
		out.WriteString("--- " + alias + " ---\n")
		doc, err := goDoc(alias)
		if err != nil {
			return nil, err
		}
		out.Write(doc)
		out.WriteByte('\n')
	}
	return bytes.ReplaceAll(out.Bytes(), []byte("\r\n"), []byte("\n")), nil
}

func goDoc(symbol string) ([]byte, error) {
	cmd := exec.Command("go", "doc", "-all", symbol)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("go doc %s: %w: %s", symbol, err, bytes.TrimSpace(output))
	}
	return bytes.TrimSpace(output), nil
}

func exportedAliases() ([]string, error) {
	files, err := filepath.Glob("*.go")
	if err != nil {
		return nil, err
	}
	aliases := make(map[string]struct{})
	for _, filename := range files {
		if strings.HasSuffix(filename, "_test.go") {
			continue
		}
		fileAliases, err := exportedAliasesInFile(filename)
		if err != nil {
			return nil, err
		}
		for _, alias := range fileAliases {
			aliases[alias] = struct{}{}
		}
	}
	result := make([]string, 0, len(aliases))
	for alias := range aliases {
		result = append(result, alias)
	}
	slices.Sort(result)
	return result, nil
}

func exportedAliasesInFile(filename string) ([]string, error) {
	file, err := parser.ParseFile(token.NewFileSet(), filename, nil, parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}
	imports := importNames(file)
	var aliases []string
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			if alias, ok := exportedAlias(spec, imports); ok {
				aliases = append(aliases, alias)
			}
		}
	}
	return aliases, nil
}

func exportedAlias(spec ast.Spec, imports map[string]string) (string, bool) {
	typeSpec := spec.(*ast.TypeSpec)
	if !typeSpec.Assign.IsValid() || !typeSpec.Name.IsExported() {
		return "", false
	}
	selector, ok := typeSpec.Type.(*ast.SelectorExpr)
	if !ok {
		return "", false
	}
	prefix, ok := selector.X.(*ast.Ident)
	if !ok {
		return "", false
	}
	importPath, ok := imports[prefix.Name]
	return importPath + "." + selector.Sel.Name, ok
}

func importNames(file *ast.File) map[string]string {
	imports := make(map[string]string, len(file.Imports))
	for _, spec := range file.Imports {
		importPath, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		name := path.Base(importPath)
		if spec.Name != nil {
			name = spec.Name.Name
		}
		if name != "_" && name != "." {
			imports[name] = importPath
		}
	}
	return imports
}

func firstDifference(want, got []byte) (line int, before, after string) {
	wantLines := strings.Split(string(want), "\n")
	gotLines := strings.Split(string(got), "\n")
	limit := min(len(wantLines), len(gotLines))
	for i := range limit {
		if wantLines[i] != gotLines[i] {
			return i + 1, wantLines[i], gotLines[i]
		}
	}
	if len(wantLines) > limit {
		before = wantLines[limit]
	}
	if len(gotLines) > limit {
		after = gotLines[limit]
	}
	return limit + 1, before, after
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "api-surface:", err)
	os.Exit(1)
}
